### ISSUE TITLE
Detect current biome by temperature and humidity

### ISSUE THREAD

**Issue by tacotexmex** [thePalindrome/biome_magic#1]
I think if you 
1. use the method to get temperatury and humididy presented in tempidity [here](https://github.com/HeroOfTheWinds/tempidity/blob/master/init.lua#L93-L98), 

2. you should be able to map those values to the values `heat_point` and `humidity_point` entered in MTGs mapgen, for example [here](https://github.com/minetest/minetest_game/blob/4ccafd15187cf70d06d68ad3931912a3c3c4b4f5/mods/default/mapgen.lua#L1193-L1194),
3. thereby being able to deduct what biome a player is located in for the moment. (Some biomes have the same climate, but those are usually "sub-biomes" such as rainforest's swamp.)

If `heat_point` and `humidity_point` isn't exposed, the method is still valuable just by copying and hardcoding them. If mgv7 is tweaked in a subgame that isn't MTG, those values will then have to be replicated in this mod, but that's for subgame makers to worry about imo.

**Comment by thePalindrome** [comment]
Do note that mgv7 is *not* the default except in 0.5.0-dev, which is getting a 'proper' biome detection function soon (from a conversation I had with paramat)

This code will be handy though, thanks for finding it ;)

**Comment by tacotexmex** [comment]
You're right, I discovered https://github.com/minetest/minetest/issues/3685 mentioning it being on the horizon, so that's good. 0.5 is still far away though iirc.

**Comment by thePalindrome** [comment]
Alright, after making all that code it turns out the temperature varies wildly depending on where you are *in* the biome. In a test world I've made, I'm at temp of -3 and humidity of 65.67, which I'm not even sure what it corresponds to. I *may* be able to get something going with this, but until then it's back to the drawing board.

For reference, I could tell I was in a savanna (sic), which should have a temp of 89 and a humidity of 42, so I think I'm grabbing the noise in the wrong spots

**Comment by tacotexmex** [comment]
I didn’t know the values change within biomes, but yes, that makes this approach useless.
